# Generated by Django 2.0.7 on 2018-08-11 16:11

from django.db import migrations

def populate_membershiptypes(apps, schema_editor):
    MembershipType=apps.get_model('sdcpeople', 'MembershipType')
    MembershipType.objects.bulk_create([
        #current quorum
        MembershipType(name="Precinct Member", order=1, counts_quorum=True),
        #current non-quorum
        MembershipType(name="Ex-Officio Member", order=2, counts_quorum=False),
        MembershipType(name="At Large Member", order=3, counts_quorum=False),
        #potential
        MembershipType(name="Pending Member", order=3, counts_quorum=False),
        MembershipType(name="Prospective Member", order=3, counts_quorum=False),
        #non-member-positive
        MembershipType(name="Supporter", order=3, counts_quorum=False),
        MembershipType(name="Follower", order=3, counts_quorum=False),
        #non-member-neutral-or-negative
        MembershipType(name="Censured", order=3, counts_quorum=False),
    ]) 


class Migration(migrations.Migration):

    dependencies = [
        ('sdcpeople', 'data01_populate_districttype'),
    ]

    operations = [
        migrations.RunPython(populate_membershiptypes)
    ]
    
