# Generated by Django 2.0.7 on 2018-08-12 14:55

from django.db import migrations

def populate_grouptype(apps, schema_editor):
    GroupType=apps.get_model('sdcpeople', 'GroupType')
    GroupType.objects.bulk_create([
        GroupType(name='Executive Committee', order=1),
        GroupType(name='Standing Committee', order=2),
        GroupType(name='Non-Standing Committee', order=3),
        GroupType(name='Workgoup', order=4),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('sdcpeople', 'data02_populate_membershiptype'),
    ]

    operations = [
        migrations.RunPython(populate_grouptype)
    ]
